# default config
baseurl = "https://demo.gethugothemes.com/parsa/site/"
languageCode = "en-us"
title = "Discover & Learn"
theme = "parsa-hugo"
summaryLength = "10"
pagination.pagerSize = 6
# google analytics
googleAnalytics = "" # example : UA-123-45
[caches]
  [caches.images]
    dir = ':cacheDir/images'
