
# navigation
[[main]]
name = "Home"
url = ""
weight = 1


[[main]]
name = "Topics"
url = ""
weight = 2
hasChildren = true


[[main]]
parent = "Topics"
name = "All topics"
url = ""
weight = 1


[[main]]
parent = "Topics"
name = "Activities"
url = "/categories/activities"
weight = 2

[[main]]
parent = "Topics"
name = "Hardware"
url = "/categories/hardware"
weight = 3

[[main]]
parent = "Topics"
name = "Leaflets"
url = "/categories/leaflets"
weight = 4

[[main]]
parent = "Topics"
name = "ARCHER2 EPCC outreach online interactive site"
url = "https://outreach.epcc.ed.ac.uk/"
weight = 5

[[main]]
name = "About"
url = "about/"
weight = 3
